spring:
  application:
    name: skip

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.80.13:3306/testdb
    username: hello
    password: hello1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: 192.168.80.13
      port: 6379

  profiles:
    include: security

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.springframework.security: debug

file:
  upload-path: C:/uploads/

biz:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/status
    serviceKey: dWa084asCEVdCW6xMVRx2B8hj2AHumB1QPv47m53+C2qlypMiXrz9pyr8e3XnnpiBWp5ZKGi8rlu0Ve3Kqbnfg==