api:
  host: localhost
  port: 8080

database:
  host: 192.168.80.13

spring:
  application:
    name: skip

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/testdb # 권새미 데이터베이스 설정
#    username: hello
#    password: hello1234
#    url: jdbc:mariadb://192.168.80.13:3306/sy  # 이상엽 데이터베이스 설정
#    username: hello
#    password: hello1234

#    url: jdbc:mariadb://${database.host}:3306/projectdb # 오정빈 데이터베이스 설정
#    username: ${MARIADB_USERNAME}
#    password: ${MARIADB_PASSWORD}

    url: jdbc:mariadb://localhost:3306/projectdb # 지봉필 데이터베이스 설정
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
#      host: ${database.host}
      port: 6379

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

# security에 있는 $ 표기법은 .env 파일에 있는 변수를 불러옴. .env는 반드시 .gitignore에 .env가 포함된 걸 먼저 확인하고 커밋한 후에 프로젝트 루트 폴더에 넣어야함
  security:
    jwt:
      key: ${JWT_SECRET_KEY}

    oauth2:
      client:
        custom-naver:
          redirect-uri: http://${api.host}:${api.port}/user/social/link/naver

        custom-kakao:
          redirect-uri: http://${api.host}:${api.port}/user/social/link/kakao

        registration:

          naver:
            client-name: Naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://${api.host}:${api.port}/login/oauth2/code/naver
            scope:
              - name
              - nickname
              - profile_image
              - email
              - phone

          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://${api.host}:${api.port}/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: kernel1913@gmail.com
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: debug

file:
  upload-path: C:/uploads/

biz:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/status
    serviceKey: ${BIZ_API_KEY}

iamport:
  apiKey: ${IAMPORT_API_KEY}
  secretKey: ${IAMPORT_SECRET_KEY}