spring:
  application:
    name: skip

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.80.13:3306/projectdb
    username: hello
    password: hello1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

file:
  upload-path: C:/uploads/